// export const SEARCH_BY_CATEGORY='SEARCH_BY_CATEGORY';
// export const SEARCH_BY_LOCATION='SEARCH_BY_LOCATION';
// export const SEARCH_BY_TEXT='SEARCH_BY_TEXT';
// export const GET_ALL_CATEGORIES='GET_ALL_CATEGORIES';
// export const GET_BUSIENESS_BY_CATEGORY='GET_BUSIENESS_BY_CATEGORY'
// export const SET_CURRENT_CATEGORY_ID='SET_CURRENT_CATEGORY_ID';
